#!/bin/bash

# Stolen from PSU:
# https://wikispaces.psu.edu/display/clcmaclinuxwikipublic/First+Boot+Script

echo "Waiting for network access"
/usr/sbin/scutil -w State:/Network/Global/DNS -t 180
sleep 5

# Get the serial number
serial=`system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' | tr '[:upper:]' '[:lower:]'`

sudo puppet agent -t --waitforcert 20 --server puppet.reallifechurch.org --certname ${serial}


/usr/bin/touch /Users/Shared/.com.googlecode.munki.checkandinstallatstartup

sudo reboot now
